# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.models.field_type import FieldType


class TestFieldType(unittest.TestCase):
    """ FieldType unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldType(self):
        """
        Test FieldType
        """
        model = picketer.models.field_type.FieldType()


if __name__ == '__main__':
    unittest.main()
