# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.apis.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """ EventsApi unit test stubs """

    def setUp(self):
        self.api = picketer.apis.events_api.EventsApi()

    def tearDown(self):
        pass

    def test_event_details(self):
        """
        Test case for event_details

        Get event details by ID
        """
        pass

    def test_event_images(self):
        """
        Test case for event_images

        Get event images
        """
        pass

    def test_search_events(self):
        """
        Test case for search_events

        Event search
        """
        pass


if __name__ == '__main__':
    unittest.main()
