# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.models.social import Social


class TestSocial(unittest.TestCase):
    """ Social unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSocial(self):
        """
        Test Social
        """
        model = picketer.models.social.Social()


if __name__ == '__main__':
    unittest.main()
