# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.apis.attractions_api import AttractionsApi


class TestAttractionsApi(unittest.TestCase):
    """ AttractionsApi unit test stubs """

    def setUp(self):
        self.api = picketer.apis.attractions_api.AttractionsApi()

    def tearDown(self):
        pass

    def test_attraction_details(self):
        """
        Test case for attraction_details

        Get attraction details by ID
        """
        pass

    def test_search_attractions(self):
        """
        Test case for search_attractions

        Search attractions
        """
        pass


if __name__ == '__main__':
    unittest.main()
