# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.apis.venues_api import VenuesApi


class TestVenuesApi(unittest.TestCase):
    """ VenuesApi unit test stubs """

    def setUp(self):
        self.api = picketer.apis.venues_api.VenuesApi()

    def tearDown(self):
        pass

    def test_search_venues(self):
        """
        Test case for search_venues

        Venue search
        """
        pass

    def test_venue_details(self):
        """
        Test case for venue_details

        Get venue details by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
