# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import picketer
from picketer.rest import ApiException
from picketer.models.end_time import EndTime


class TestEndTime(unittest.TestCase):
    """ EndTime unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndTime(self):
        """
        Test EndTime
        """
        model = picketer.models.end_time.EndTime()


if __name__ == '__main__':
    unittest.main()
