# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Address(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, line_1=None, line_2=None, line_3=None):
        """
        Address - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'line_1': 'str',
            'line_2': 'str',
            'line_3': 'str'
        }

        self.attribute_map = {
            'line_1': 'line_1',
            'line_2': 'line_2',
            'line_3': 'line_3'
        }

        self._line_1 = line_1
        self._line_2 = line_2
        self._line_3 = line_3

    @property
    def line_1(self):
        """
        Gets the line_1 of this Address.

        :return: The line_1 of this Address.
        :rtype: str
        """
        return self._line_1

    @line_1.setter
    def line_1(self, line_1):
        """
        Sets the line_1 of this Address.

        :param line_1: The line_1 of this Address.
        :type: str
        """

        self._line_1 = line_1

    @property
    def line_2(self):
        """
        Gets the line_2 of this Address.

        :return: The line_2 of this Address.
        :rtype: str
        """
        return self._line_2

    @line_2.setter
    def line_2(self, line_2):
        """
        Sets the line_2 of this Address.

        :param line_2: The line_2 of this Address.
        :type: str
        """

        self._line_2 = line_2

    @property
    def line_3(self):
        """
        Gets the line_3 of this Address.

        :return: The line_3 of this Address.
        :rtype: str
        """
        return self._line_3

    @line_3.setter
    def line_3(self, line_3):
        """
        Sets the line_3 of this Address.

        :param line_3: The line_3 of this Address.
        :type: str
        """

        self._line_3 = line_3

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Address):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
