# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Area(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, type=None, rank=None, area_type=None):
        """
        Area - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'type': 'str',
            'rank': 'str',
            'area_type': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'rank': 'rank',
            'area_type': 'area-type'
        }

        self._id = id
        self._name = name
        self._type = type
        self._rank = rank
        self._area_type = area_type

    @property
    def id(self):
        """
        Gets the id of this Area.

        :return: The id of this Area.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Area.

        :param id: The id of this Area.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Area.

        :return: The name of this Area.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Area.

        :param name: The name of this Area.
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """
        Gets the type of this Area.

        :return: The type of this Area.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Area.

        :param type: The type of this Area.
        :type: str
        """

        self._type = type

    @property
    def rank(self):
        """
        Gets the rank of this Area.

        :return: The rank of this Area.
        :rtype: str
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """
        Sets the rank of this Area.

        :param rank: The rank of this Area.
        :type: str
        """

        self._rank = rank

    @property
    def area_type(self):
        """
        Gets the area_type of this Area.

        :return: The area_type of this Area.
        :rtype: str
        """
        return self._area_type

    @area_type.setter
    def area_type(self, area_type):
        """
        Sets the area_type of this Area.

        :param area_type: The area_type of this Area.
        :type: str
        """

        self._area_type = area_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Area):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
