# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EventImages(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, links=None, type=None, id=None, images=None):
        """
        EventImages - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'links': 'Links',
            'type': 'str',
            'id': 'str',
            'images': 'list[Image]'
        }

        self.attribute_map = {
            'links': '_links',
            'type': 'type',
            'id': 'id',
            'images': 'images'
        }

        self._links = links
        self._type = type
        self._id = id
        self._images = images

    @property
    def links(self):
        """
        Gets the links of this EventImages.

        :return: The links of this EventImages.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this EventImages.

        :param links: The links of this EventImages.
        :type: Links
        """

        self._links = links

    @property
    def type(self):
        """
        Gets the type of this EventImages.

        :return: The type of this EventImages.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EventImages.

        :param type: The type of this EventImages.
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """
        Gets the id of this EventImages.

        :return: The id of this EventImages.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this EventImages.

        :param id: The id of this EventImages.
        :type: str
        """

        self._id = id

    @property
    def images(self):
        """
        Gets the images of this EventImages.

        :return: The images of this EventImages.
        :rtype: list[Image]
        """
        return self._images

    @images.setter
    def images(self, images):
        """
        Sets the images of this EventImages.

        :param images: The images of this EventImages.
        :type: list[Image]
        """

        self._images = images

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EventImages):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
