# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GeneralInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, general_rule=None, child_rule=None):
        """
        GeneralInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'general_rule': 'str',
            'child_rule': 'str'
        }

        self.attribute_map = {
            'general_rule': 'generalRule',
            'child_rule': 'childRule'
        }

        self._general_rule = general_rule
        self._child_rule = child_rule

    @property
    def general_rule(self):
        """
        Gets the general_rule of this GeneralInfo.

        :return: The general_rule of this GeneralInfo.
        :rtype: str
        """
        return self._general_rule

    @general_rule.setter
    def general_rule(self, general_rule):
        """
        Sets the general_rule of this GeneralInfo.

        :param general_rule: The general_rule of this GeneralInfo.
        :type: str
        """

        self._general_rule = general_rule

    @property
    def child_rule(self):
        """
        Gets the child_rule of this GeneralInfo.

        :return: The child_rule of this GeneralInfo.
        :rtype: str
        """
        return self._child_rule

    @child_rule.setter
    def child_rule(self, child_rule):
        """
        Sets the child_rule of this GeneralInfo.

        :param child_rule: The child_rule of this GeneralInfo.
        :type: str
        """

        self._child_rule = child_rule

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GeneralInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
