# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Image(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url=None, ratio=None, width=None, height=None, fallback=None, attribution=None):
        """
        Image - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'url': 'str',
            'ratio': 'str',
            'width': 'str',
            'height': 'str',
            'fallback': 'bool',
            'attribution': 'str'
        }

        self.attribute_map = {
            'url': 'url',
            'ratio': 'ratio',
            'width': 'width',
            'height': 'height',
            'fallback': 'fallback',
            'attribution': 'attribution'
        }

        self._url = url
        self._ratio = ratio
        self._width = width
        self._height = height
        self._fallback = fallback
        self._attribution = attribution

    @property
    def url(self):
        """
        Gets the url of this Image.

        :return: The url of this Image.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this Image.

        :param url: The url of this Image.
        :type: str
        """

        self._url = url

    @property
    def ratio(self):
        """
        Gets the ratio of this Image.

        :return: The ratio of this Image.
        :rtype: str
        """
        return self._ratio

    @ratio.setter
    def ratio(self, ratio):
        """
        Sets the ratio of this Image.

        :param ratio: The ratio of this Image.
        :type: str
        """

        self._ratio = ratio

    @property
    def width(self):
        """
        Gets the width of this Image.

        :return: The width of this Image.
        :rtype: str
        """
        return self._width

    @width.setter
    def width(self, width):
        """
        Sets the width of this Image.

        :param width: The width of this Image.
        :type: str
        """

        self._width = width

    @property
    def height(self):
        """
        Gets the height of this Image.

        :return: The height of this Image.
        :rtype: str
        """
        return self._height

    @height.setter
    def height(self, height):
        """
        Sets the height of this Image.

        :param height: The height of this Image.
        :type: str
        """

        self._height = height

    @property
    def fallback(self):
        """
        Gets the fallback of this Image.

        :return: The fallback of this Image.
        :rtype: bool
        """
        return self._fallback

    @fallback.setter
    def fallback(self, fallback):
        """
        Sets the fallback of this Image.

        :param fallback: The fallback of this Image.
        :type: bool
        """

        self._fallback = fallback

    @property
    def attribution(self):
        """
        Gets the attribution of this Image.

        :return: The attribution of this Image.
        :rtype: str
        """
        return self._attribution

    @attribution.setter
    def attribution(self, attribution):
        """
        Sets the attribution of this Image.

        :param attribution: The attribution of this Image.
        :type: str
        """

        self._attribution = attribution

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Image):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
