# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Links(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _self=None, next=None, prev=None):
        """
        Links - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_self': 'Link',
            'next': 'Link',
            'prev': 'Link'
        }

        self.attribute_map = {
            '_self': 'self',
            'next': 'next',
            'prev': 'prev'
        }

        self.__self = _self
        self._next = next
        self._prev = prev

    @property
    def _self(self):
        """
        Gets the _self of this Links.

        :return: The _self of this Links.
        :rtype: Link
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """
        Sets the _self of this Links.

        :param _self: The _self of this Links.
        :type: Link
        """

        self.__self = _self

    @property
    def next(self):
        """
        Gets the next of this Links.

        :return: The next of this Links.
        :rtype: Link
        """
        return self._next

    @next.setter
    def next(self, next):
        """
        Sets the next of this Links.

        :param next: The next of this Links.
        :type: Link
        """

        self._next = next

    @property
    def prev(self):
        """
        Gets the prev of this Links.

        :return: The prev of this Links.
        :rtype: Link
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """
        Sets the prev of this Links.

        :param prev: The prev of this Links.
        :type: Link
        """

        self._prev = prev

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
