# coding: utf-8

"""
    Ticketmaster Discovery API

    Swagger spec based on Ticketmaster Discovery API

    OpenAPI spec version: 1.0.0
    Contact: git@edward.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SegmentDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, links=None, embedded=None, id=None, name=None):
        """
        SegmentDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'links': 'Links',
            'embedded': 'Embedded',
            'id': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'links': '_links',
            'embedded': '_embedded',
            'id': 'id',
            'name': 'name'
        }

        self._links = links
        self._embedded = embedded
        self._id = id
        self._name = name

    @property
    def links(self):
        """
        Gets the links of this SegmentDetails.

        :return: The links of this SegmentDetails.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this SegmentDetails.

        :param links: The links of this SegmentDetails.
        :type: Links
        """

        self._links = links

    @property
    def embedded(self):
        """
        Gets the embedded of this SegmentDetails.

        :return: The embedded of this SegmentDetails.
        :rtype: Embedded
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """
        Sets the embedded of this SegmentDetails.

        :param embedded: The embedded of this SegmentDetails.
        :type: Embedded
        """

        self._embedded = embedded

    @property
    def id(self):
        """
        Gets the id of this SegmentDetails.

        :return: The id of this SegmentDetails.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SegmentDetails.

        :param id: The id of this SegmentDetails.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this SegmentDetails.

        :return: The name of this SegmentDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SegmentDetails.

        :param name: The name of this SegmentDetails.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SegmentDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
